### ISSUE TITLE
ImportError: No module named 'Model'

### ISSUE THREAD

**Issue by thiscantbetaken** [jmtomczak/vae_vampprior#1]
Trying to get this working today, but I'm getting the following error:

# python experiment.py --dataset_name=cifar10
load data
Files already downloaded and verified
create model
Traceback (most recent call last):
  File "experiment.py", line 160, in <module>
    run(args, kwargs)
  File "experiment.py", line 124, in run
    from models.VAE import VAE
  File "/workspace/vae_vampprior/models/VAE.py", line 20, in <module>
    from Model import Model
ImportError: No module named 'Model'

Any ideas?

**Comment by jmtomczak** [comment]
Please check whether you have the latest version of the code. I have added at some point a general class of a model (Model.py).

**Comment by jramapuram** [comment]
I think what needs to be done here is call it as such: `from models.Model import Model` . Fixed in https://github.com/jmtomczak/vae_vampprior/pull/2

**Comment by alexryan** [comment]
minimum_working_example/tendies-basic-tutorial.ipynb:
ModuleNotFoundError: No module named 'model'

**Comment by adithyak2k03** [comment]
what is the most recent fix for this error?
